config/routes.rb
ParseRailsBoilerplate::Application.routes.draw do
  get "log_in" => "sessions#new", as: "log_in"
  get "log_out" => "sessions#destroy", as: "log_out"
  get "sign_up" => "users#new", as: "sign_up"

  resources :sessions

  resources :users do
    collection do
      get :manage
    end
  end
  
  resources :projects do
    member do
      get :archive
    end
  end

  namespace :api do
    resources :mailers do
      collection do
        post :send_mail
      end
    end
  end
  
  resources :issues do
  	collection do
  		get :fetch_issue, :pdf_report, :report, :fetch_issue_report, :sample_issues_csv
      post :upload_issues
  	end
  end

  root to: "issues#index"
end

app/models/issue.rb
class Issue < ParseResource::Base
  fields :Project, :Description, :mitigationPlan, :dateIdentified, :dateResolved, :Status, :Severity, :CommentsArray, :title, :isManagementIssue

  belongs_to :project
end

app/models/issue_types.rb
class IssueTypes < ParseResource::Base
  fields :objectId, :IssueType, :ACL
end

app/models/issues.rb
class Issues < ParseResource::Base
	 
  fields :Project, :Description, :mitigationPlan, :dateIdentified, :dateResolved, :Status, :Severity, :CommentsArray, :title, :isManagementIssue, :IssueType, :isClientIssue, :ProjectOwner, :AccountManager

  validates :Description, :Severity, presence: true

  def self.import(file, current_userName)
    spreadsheet = open_spreadsheet(file)
    header = spreadsheet.row(1)
    (2..spreadsheet.last_row).each do |i|
      row = Hash[[header, spreadsheet.row(i)].transpose]
      create_issue(row, current_userName) if !row["title"].blank? && find_by_title(row["title"]).blank?
    end
  end

  def self.open_spreadsheet(file)
    case File.extname(file.original_filename)
    when ".xlsx" then Roo::Excelx.new(file.path, packed: nil, file_warning: :ignore)
    else raise "Unknown file type: #{file.original_filename}"
    end
  end

  def self.create_issue(row, current_userName)
    row = row.select {|k,v| ["Project","title", "Description", 'dateIdentified', 'dateResolved', 'Status', 'Severity', "assignedTo", "isManagementIssue", "isClientIssue", "isClosed", 'closedBy', 'createdBy', 'IssueType', 'AccountManager', "ProjectOwner", "mitigationPlan"].include?(k) }
    
    row["Project"] = row["Project"].strip.upcase
    row["Status"] = row["Status"].strip.upcase
    row["Severity"] = row["Severity"].strip.upcase
    
    row["isClosed"] = (row["isClosed"] == "true" || row["isClosed"] == 1 ? true : false)
    row["isManagementIssue"] = (row["isManagementIssue"] == "true" || row["isManagementIssue"] == 1 ? true : false)
    row["isClientIssue"] = (row["isClientIssue"] == "true" || row["isClientIssue"] == 1 ? true : false)
    row["isDeleted"] = false

    row["assignedTo"] = 'RAJAT JULKA' if row["isManagementIssue"] == true
    row["assignedTo"] = row["assignedTo"].blank? ? 'RAJAT JULKA' : row["assignedTo"].strip.upcase!

    row["createdBy"] = current_userName
    row["CommentsArray"] = []

    # Create the record for the issue.
    issue = Issues.new(row) 
    raise 'Headers/values are not in proper format' and return unless issue.save
  end

end

app/controllers/issues_controller.rb
require 'csv'

class IssuesController < ApplicationController
	before_filter :authenticate_user!
	before_filter :check_read, only: [:index, :fetch_issue, :create, :destroy]
	before_filter :mark_read, only: [:show, :edit]
	
	def index
    archived = Project.archived.include?(params[:project]) if params[:project].present?

    if archived
      flash[:notice] = "Project #{params[:project]} has been archived!"
      redirect_to '/'
    end

    @issues = if params[:project] && params[:project] != 'ALL'
      issue_query(params[:project])
    else
      issue_query
    end
    @serverty, @closed  = category(@issues)
		#@projects = all_projects @issues # Moin - remove if all well
		#@users = all_users # Moin - remove if all well
	end	


	def fetch_issue
		@issues = params[:project] == "ALL" ?	issue_query : issue_query(params[:project])
		@serverty, @closed  = category(@issues)
		format_create response
	end

	def create
		@issues = []
		params[:issues][:isClosed] = params[:issues][:isClosed] == "true" ? true : false
		params[:issues][:isManagementIssue] = params[:issues][:isManagementIssue] == "true" ? true : false
		params[:issues][:isClientIssue] = params[:issues][:isClientIssue] == "true" ? true : false
		params[:issues][:isDeleted] = false

    assigned_user_id = params[:issues][:assignedTo]
    params[:issues][:AccountManager] = params[:issues][:AccountManager]
		params[:issues][:ProjectOwner] = params[:issues][:ProjectOwner]

    # Set assigned_to with UserId name.
    params[:issues][:assignedTo] = User.find_by_objectId(assigned_user_id).Name unless params[:issues][:assignedTo].blank?

		params[:issues][:assignedTo] = 'RAJAT JULKA' if params[:issues][:assignedTo].blank?
		params[:issues][:createdBy] = current_user.Name
		params[:issues][:Project] = ((params[:issues][:Project]).strip).upcase
		params[:issues][:CommentsArray] = []
		@issue = Issues.new(params[:issues])

		if @issue.save
			# @issues = issue_query params[:issues][:Project]
			send_mail @issue if params[:issues][:Status] == "CLOSED"
			send_notification "create", @issue, assigned_user_id
			# UserNotifier.send_create_notification_mail(@issue).deliver!
			@issues = params[:project] == "ALL" ?	issue_query : issue_query(params[:project]) if params[:project]
			@serverty, @closed  = category(@issues)
		else
			@issues = params[:project] == "ALL" ?	issue_query : issue_query(params[:project]) if params[:project]
			@serverty, @closed  = category(@issues)
		end
		format_create response
	end

	def upload_issues
    if request.post?
      if params[:file].blank?
        flash[:notice] = "Pleae provide file to upload in xlsx format." 
      else
        if get_file_format(params[:file]) == 'xlsx'
          begin
            Issues.import(params[:file], current_user.Name)
            flash[:notice] ="Issues imported successfully" 

          rescue Exception => e
            flash[:error] = "#{e}" 
            redirect_to '/issues' and return
          end
        else
          flash[:error] = "Invalid file format, Please upload .xlsx file."
        end
      end
      redirect_to '/issues'
    end
	end

	def sample_issues_csv
		# headers_for_csv = ["S.No", "Project", "Title", "Description", "MitigationPlan", "DateIdentified", "Status", "Severity", "assignedTo", "Is Management Issue"]
    dir_path = "#{Rails.root}/"
    FileUtils.mkdir_p(dir_path) unless File.directory?(dir_path)
    file_name = 'upload_cuts_sample_format.xlsx'
    file_path = "#{dir_path}/#{file_name}"

    # CSV.open(file_path, "w") do |file|
    #   file << headers_for_csv
    #   file << ["1", "LinkYogi", "My first Cut title", "My first Cut description", "Plan detail", "26-10-2015", "OPEN/IN-PROGRESS/CLOSED/ASSIGNED/ON HOLD/RESOLVED", "LOW/MEDIUM/HIGH", "UserName", "true/false"]
    # end

    send_data File.read(file_path), :filename => 'upload_cuts_sample_format.xlsx', :disposition => 'attachment'

  # spreadsheet = StringIO.new 
  # book.write spreadsheet 
  # send_data spreadsheet.string, :filename => "yourfile.xls", :type =>  "application/vnd.ms-excel"
	end

	def edit
		@object_issues = Issues.find_by_objectId(params[:id])
		if @object_issues.nil?
			flash[:notice] = "Issue not found"
			redirect_to issues_path, :notice => "Cut not found"
		end
	end

	def show
		@object_issues = Issues.find_by_objectId(params[:id])
    
		if @object_issues.nil?
			flash[:notice] = "Issue not found"
			redirect_to issues_path, :notice => "Cut not found"
		end
		@users = all_users	
	end

	def update
		@object_issues = Issues.find_by_objectId(params[:id])
		closed_status = (@object_issues.Status == "CLOSED")
		params[:issues][:isClosed] = params[:issues][:Status] == "CLOSED" ? true : false
		params[:issues][:closedBy] = params[:issues][:Status] == "CLOSED" ? current_user.Name : ''

    assigned_user_id = params[:issues][:assignedTo]
    # Set assigned_to with UserId name.
    params[:issues][:assignedTo] = User.find_by_objectId(assigned_user_id).Name unless params[:issues][:assignedTo].blank?
    params[:issues][:AccountManager] = User.find_by_objectId(assigned_user_id).Name unless params[:issues][:AccountManager].blank?
    params[:issues][:ProjectOwner] = User.find_by_objectId(assigned_user_id).Name unless params[:issues][:ProjectOwner].blank?

		params[:issues][:assignedTo] = 'RAJAT JULKA' if params[:issues][:assignedTo].blank?
		params[:issues][:isManagementIssue] = params[:issues][:isManagementIssue] == "1" ? true : false
		params[:issues][:isClientIssue] = params[:issues][:isClientIssue] == "1" ? true : false
		comment = [[params[:issues][:CommentsArray],"Update By #{current_user.username} on #{Time.now.strftime("%d-%m-%Y %I:%M:%S")}"]]
		if (@object_issues.CommentsArray.nil? || @object_issues.CommentsArray.blank? ) && !params[:issues][:CommentsArray].blank?
			params[:issues][:CommentsArray] = comment
		elsif ( !@object_issues.CommentsArray.nil? || !@object_issues.CommentsArray.blank?) && params[:issues][:CommentsArray].blank?	
			# params[:issues][:CommentsArray] = @object_issues.CommentsArray
			params[:issues].delete :CommentsArray
		elsif ( !@object_issues.CommentsArray.nil? || !@object_issues.CommentsArray.blank?) && !params[:issues][:CommentsArray].blank?
			params[:issues][:CommentsArray] = @object_issues.CommentsArray + comment	
		elsif (@object_issues.CommentsArray.nil? || @object_issues.CommentsArray.blank?) && params[:issues][:CommentsArray].blank?
			# params[:issues][:CommentsArray] = []
			params[:issues].delete :CommentsArray
		end	
		params[:issues][:lastUpdatedBy] = current_user.Name
		params[:issues][:Project] = ((params[:issues][:Project]).strip).upcase	
		@issue = @object_issues.update_attributes(params[:issues])
		
		if @issue
			# send_notification "update", @object_issues, assigned_user_id
			mark_unread @object_issues.objectId
			if params[:issues][:Status] == "CLOSED" && !closed_status
				# send_mail @object_issues
			else	
				# UserNotifier.send_update_notification_mail(@object_issues).deliver!
			end
		end
		# @serverty, @closed  = category(@issues)	
		redirect_to issues_path(:project => params[:project])
	end


	def destroy 
		issue = Issues.find_by_objectId(params[:id])
		issue_create = issue.update_attributes(:isDeleted => true ,:deletedBy => current_user.Name,:lastUpdatedBy => current_user.Name) if issue 

    assigned_user_id = User.find_by_Name(issue.assignedTo).objectId
		if issue_create
			# send_notification "delete", issue, assigned_user_id
			mark_unread issue.objectId
			# UserNotifier.send_delete_notification_mail(issue).deliver!
		end	
		@issues = params[:project] == "ALL" ?	issue_query : issue_query(params[:project]) if params[:project]
		@issues = issue_query if @issues.blank?
		@serverty, @closed  = category(@issues)	
		format_create response	
	end	

	def issue_query(project = nil)
		issues = Issues.where(query(project)).all
		unless current_user.isAdmin
			issues = issues + Issues.where(get_created_by_data(project)).all
		end
    archived_projects = Project.archived
    issues.select {|issue| !archived_projects.include?(issue.Project) }
	end

  def query(project)
    query = { isDeleted: false }
    query.merge!(assignedTo: current_user.Name) unless current_user.isAdmin
    query.merge!(Project: project) if project
    query
  end

	def get_created_by_data(project)
		query = { isDeleted: false }
		query.merge!(createdBy: current_user.Name)
		query.merge!(Project: project)  if project
		query
	end

	def format_create response
		respond_to do |format|
			format.html { render :partial => "project_list" , :layout => false }
		end
	end	

	def report
		@users = all_users
		@issues_obj = issue_query
		@issues = []
		@projects = @issues_obj.map(&:Project).uniq if @issues_obj
		@projects.collect! { |c| [ c, c ] unless c.nil?}  if @projects
	end	

	def fetch_issue_report
		@issues = setupdata params
		respond_to do |format|
			format.html { render :partial => "project_list_report" , :layout => false }
		end
	end	
	def pdf_report
		@issues = setupdata params
		respond_to do |format|
			format.html
			format.pdf do
				render	:pdf => "sample",
								:header => {:html => { :template => 'issues/header.html.erb'}, :spacing => 5},
								:footer => {:html => { :template => 'issues/footer.html.erb'}}
      end
    end
  end	

  def send_mail object
  	UserNotifier.send_close_notification_mail(object).deliver!
  end	

  def setupdata params
  	if params[:project] == "ALL"
  		@issues = issue_query
  		@issues.select{|issue| ((params[:start_date].to_date)..(params[:end_date].to_date)) === issue.dateIdentified.to_date }
  	else
  		@issues = issue_query params[:project]
  		@issues.select{|issue| ((params[:start_date].to_date)..(params[:end_date].to_date)) === issue.dateIdentified.to_date }
  	end
  end	

  def all_users
  	users =  current_user.isAdmin ? User.all.map(&:Name) : ['RAJAT JULKA']
  	users.collect! { |c| [ c, c ] } if users
  end

  def all_projects issues
  	projects = @issues.map(&:Project).uniq if issues

app/helpers/issues_helper.rb
module IssuesHelper

  def image_icon arg
    case arg
    when 'HIGH' then 'h_red_icon.png'
    when 'MEDIUM' then 'm_blue.png'
    when 'LOW' then 'l_green_icon.png'
    else 'l_green_icon.png'
    end
  end	

  def status
    [
      ["OPEN","OPEN"],
      ["CLOSED","CLOSED"],
      ["RESOLVED","RESOLVED"]
    ]
  end

  def servity
    [["LOW","LOW"],["MEDIUM","MEDIUM"],["HIGH","HIGH"]]
  end	

end

app/views/issues/_comments.html.erb
<!-- # Refactor -->
<div class="col-sm-12">
  <h4 style="padding: 7px;background: #CCC;">Audit Trails</h4>
  <% (comments.reverse).each do |comment| %>
    <% data = comment[1].split(' ') %>
    <span >
      <span style="color: #428BCA;">Audit Trail For :</span>
      <b><%= "#{data[4]} #{data[5]}" %></b>
    </span>
    <br/>
    <span >
      <span style= "color: #428BCA;">Created By :</span>
      <b><%= "#{data[2]}" %></b>
    </span>
    <br/>
    <span>
      <span style="color: #428BCA;float: left;margin-right: 5px;">Note :</span>
      <%= simple_format(comment[0]) %>
    </span>
    <hr/>
  <% end %>
</div>

app/views/issues/_create-old.html.erb
<form class="form-horizontal" , id = "new_issue_create_form">  
  <div class="control-group">

    <div class="col-sm-12">
      <div class="col-sm-12">
        <label class="" for="input01">Cut Title<span style="color: #FF0000;padding: 4px;">*</span></label>  
        <div class="s">  
          <input type="text" class="" id="cut_title" name="title" required style="width: 65%;"> 
        </div> 
      </div>
    </div>  
    <div class="col-sm-12 create_cut_field" style="margin-top: 10px;"> 
      <div class="col-sm-4">
        <label class="" for="input01">Project</label>  
        <div class="s">  
          <!-- <input type="text" class="" id="project" name="project" required>  -->
          <%= select_tag 'project', options_for_select(projects,:selected => params[:project]) , :style=>"width: 100%;" %>
        </div> 
      </div>
      <div class="col-sm-4">
        <label class="" for="input01">Description<span style="color: #FF0000;padding: 4px;">*</span></label>  
        <div class="">
          <textarea name="description" id="description" placeholder = "Enter Description" required rows="2" cols="35" style = "width: 100%;" ></textarea>
        </div> 
      </div>
      <div class="col-sm-4">
        <label class="" for="input01">MitigationPlan</label>  
        <div class="">
          <textarea name="mitigationPlan" id="mitigationPlan" placeholder = "Enter MitigationPlan" rows="2" cols="35" style = "width: 100%;"></textarea>
        </div> 
      </div>
    </div>
    <div class="col-sm-12 create_cut_field"> 
      <div class="col-sm-4">
        <label class="" for="input01">DateIdentified</label>  
        <div class="s">  
          <input type="text" class="datepicker" id="dateIdentified" name="dateIdentified"required readonly value="<%=Date.today.strftime('%d-%m-%Y')%>">  
        </div> 
      </div>
      <div class="col-sm-4">
        <label class="" for="input01">DateResolved</label>  
        <div class="">  
          <input type="text" class="" id="dateResolved" name="dateResolved" readonly>  
        </div> 
      </div>
      <div class="col-sm-4">
        <label class="" for="input01">Status</label>  
        <div class="">
          <%= select_tag 'status', options_for_select(status)%>  
        </div> 
      </div>
    </div>
    <div class="col-sm-12 create_cut_field"> 
      <div class="col-sm-4">
        <label class="" for="input01">AccountManager</label>  
        <div class="s">  
          <%= select_tag 'accountManager', options_for_select(all_users_with_id)%>
        </div> 
      </div>
      <div class="col-sm-4">
        <label class="" for="input01">ProjectOwner</label>  
        <div class="">  
          <%= select_tag 'projectOwner', options_for_select(all_users_with_id)%>
        </div> 
      </div>
      <div class="col-sm-4">
        <label class="" for="input01">Issue Types</label>
        <div class="s">
            <%= select_tag 'issueType', options_for_select(issue_types)%>
        </div>
      </div>
    </div>
    <div class="col-sm-12 create_cut_field"> 
      <div class="col-sm-4">
        <label class="" for="input01">Severity</label>  
        <div class="">
          <%= select_tag 'severity', options_for_select(servity)%>   
        </div> 
      </div>
      <div class="col-sm-4">
        <label class="" for="input01">Assigned To</label>

        <div class="s">
          <%if current_user.isAdmin%>
            <%= select_tag 'assignedto', options_for_select(all_users_with_id, :selected => 'RAJAT JULKA') , :style => "width: 100%;"%>
          <%else%>
            <%= select_tag 'assignedto', options_for_select(all_users_with_id)%>
          <%end%>
        </div>
      </div>
      <div class="col-sm-4">
        <%if current_user.isAdmin%>
        <label class="" for="input01">Is Management Issue</label>
        <input type="checkbox" id="ismanageable" >
        <%end%>
      </div>
      <div class="col-sm-4">
        <label class="" for="input01">Is Client Issue</label>
        <input type="checkbox" id="isclientissue" >
      </div>
    </div>  
    <div class="col-sm-12 create_cut_field">
      <div class="col-sm-4">

      </div>
      <div class="col-sm-4">

      </div>
      <div class="col-sm-4">
        <!-- <button type="button" class="btn btn-primary" , id ="create_issue" style="margin-top: 23px;" >Create</button>
        <button class="btn create_new_issue" , style="margin-top: 23px;">Cancel</button> -->
      </div>
    </div>
  </div>  
</form>  

app/views/issues/_create.html.erb
<form class="form-horizontal", id="new_issue_create_form">  
  <div class="control-group">
    <div class="col-sm-12 create_cut_field" style="margin-top: 10px;"> 
      
      <div class="col-sm-4">
        <label for="input01">
          Project<span class="required">*</span>
        </label>
        <div>
          <%= select_tag 'project', options_for_select(options_for_projects_select, selected: params[:project]) , style: 'width: 100%;' %>
        </div>
      </div>

      <div class="col-sm-4">
        <label for="input01">
          Status<span class="required">*</span>
        </label>
        <div class="">
          <%= select_tag 'status', options_for_select(status)%>
        </div> 
      </div>

      <div class="col-sm-4">
        <label for="input01">
          Severity<span class="required">*</span>
        </label>
        <div>
          <%= select_tag 'severity', options_for_select(servity)%>
        </div> 
      </div>
      
    </div>

    <div class="col-sm-12 create_cut_field">
      
      <div class="col-sm-12">
        <label for="input01">
          Issue Description<span class="required">*</span>
        </label>
        <div>
          <%= text_area_tag :description, nil, placeholder: 'Enter Description', class: 'cut-area', required: true %>
          <span id='error-message' class='error-message'></span>
        </div> 
      </div>

    </div>
    
  </div>  
</form>  

app/views/issues/_project_list.html.erb
<style type="text/css">
  .dataTables_filter {
    margin-top: -49px !important;
    margin-right: 10px;
  }
  .dataTables_length{
    margin-left: 15px;
    margin-bottom: 3px;
  }
  #table-issues_filter{
    display: none !important;
  }
</style>

<div class = "project_list_div">
  <div class="panel panel-primary">
    <div class="panel-heading">Cuts</div>
    
    <div class="panel-body" id = "panel-body-active">
      <button type="button" class="btn btn-default navbar-btn filter-btn-all active" data-text="^((?!CLOSED).)*$">
        ALL ACTIVE <span class="badge" id="">
          <%=(@serverty.count - @closed.count("CLOSED")) if @serverty && @closed%>
        </span>
      </button>
      
      <button type="button" class="btn btn-default navbar-btn filter-btn-ser" data-text="HIGH">
        HIGH <span class="badge"><%=@serverty.count("HIGH") if @serverty%></span>
      </button>
      
      <button type="button" class="btn btn-default navbar-btn filter-btn-ser" data-text="MEDIUM">
        MEDIUM <span class="badge"><%=@serverty.count("MEDIUM") if @serverty%></span>
      </button>
      
      <button type="button" class="btn btn-default navbar-btn filter-btn-ser" data-text="LOW">
        LOW <span class="badge"><%=@serverty.count("LOW") if @serverty%></span>
      </button>
      
      <button type="button" class="btn btn-default navbar-btn filter-btn-stat" data-text="CLOSED" id="closed_issue_button">
        CLOSED <span class="badge" ><%=@closed.count("CLOSED") if @closed%></span>
      </button>
    </div>  
    
    <table  class="table  no-margin" id="table-issues" cellspacing="0" width="100%">
      <thead>
        <tr style="background-color: #F1EEEE;">
          <th width="5%">Severity</th>
          <th style="width: 75px !important;">Severity</th>
          <th width="60%">Issue Description</th>
          <th width="20%">Project</th>
          <th class="hide">Created By</th>
          <th class="hide">Assigned To</th>
          <th width="7%">Status</th>
          <th width="8%">Action</th>
        </tr>
      </thead>
      <tbody>
        <% issue_list = [] %>
        <% if @issues && @issues.any? %>
          <% @issues.each do |issue| %>
            <% unless issue_list.include? issue.objectId %>
              <% issue_list << issue.objectId %>
              <tr class=<%= (@read_issues.include? issue.objectId) ? 'read_issue' : 'unread_issue' %>>
                <td >
                  <%= issue.Severity %>
                </td>
                <td class=<%=issue.Severity%> style="text-align: center;">
                  <%= image_tag image_icon(issue.Severity), width: '50%' %>
                </td>
                <td>
                  <%=link_to issue.Description, issue_path(issue.objectId), class: 'title_link', title: 'Show' %>
                </td>
                <td><%= issue.Project %></td>
                <td class="hide"><%= issue.createdBy %></td>
                <td class="hide"><%= issue.assignedTo %></td>
                <td><%= issue.Status %></td>
                <td>
                  <%= link_to edit_issue_path(issue.objectId), data_id: issue.objectId, class: 'issue_update', title: "EDIT" do %>
                    <i><%= image_tag "glyphicons_150_edit.png" %></i>
                  <%end%>
                  <% if current_user.isAdmin %>
                    <%= link_to  "", data_id: issue.objectId, class: "issue_delete", title: "DELETE" do %>
                      <i><%= image_tag "glyphicons_207_remove_2.png" %></i>
                    <% end %>
                  <% end %>
                </td>
              </tr>
            <% end %>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>

  <div class='modal fade' id='delete_issue' tabindex='-1' role='dialog' aria-labelledby='myModalLabel' aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header" style="background-color: #428BCA;">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
          Delete Issue
        </div>
        <div class="modal-body">
          <p>Do you really want to delete this Issue?</p>
        </div>
        <div class="modal-footer" style="background-color: whiteSmoke;">
          <button data-dismiss="modal" class="btn btn-primary">No</button>
          <button id="id-confirm-delete" class="btn btn-danger ">Yes</button>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/issues/_project_list_report.html.erb
<style type="text/css">
  .dataTables_filter {
    margin-right: 10px;
  }
  .dataTables_length {
    margin-left: 15px;
  }
  .dataTables_wrapper {
    margin-top: 10px;
  }
</style>
<div class="panel panel-primary">
  <!-- Default panel contents -->
  <div class="panel-heading">Cuts</div>
  <table  class="table  no-margin" id="table-issues-report" cellspacing="0" width="100%" style="margin-top: 10px;">
    <thead>
      <tr style="background-color: #F1EEEE;">
        <th width="10%">Severity</th>
        <th width="30%">Project</th>
        <th width="50%">Description</th>
        <th width="10%">Status</th>
      </tr>
    </thead>
    <tbody>
    <% if @issues%>        
      <% @issues.each do |issue| %>
      <tr>
        <td class=<%=issue.Severity%> style="text-align: center;">
          <%= image_tag image_icon(issue.Severity), width: '50%' %>
        </td>
        <td><%= issue.Project %></td>
        <td><%= issue.Description %></td>
        <td><%= issue.Status %></td>
      </tr>
      <% end %>
    <%end%>     
    </tbody>
  </table>
</div>

app/views/issues/footer.html.erb
<hr style = "height:0.05em;width:100%;background:#3897B5;" />
<div style = "font-size: 10px; text-align: center;">
  <b>Regd. Office</b> : #12, Sector 8-A, Chandigarh, India : 160009  <b>Works</b> : 18S G-9, RGIT  Park, Chandigarh, India 
</div>

app/views/issues/header.html.erb
<div id = "header" style="margin-top:15%;">
 <%= wisepdf_image_tag 'Trantor.jpg' %>
 <hr style = "height:0.1em;width:100%;background:#3897B5;" />
</div>

app/views/issues/index.html.erb
<fieldset class="fieldset">
	<div class="row-fluid">
			<fieldset>
				<div class="col-sm-4">
					<label class="control-label">
            <strong style="font-size: 16px; color:#428BCA">Select Project</strong>
          </label>
					<%= select_tag 'project_list_drop', options_for_select(options_for_projects_select(true), selected: params[:project]), style: "margin-top: 8px; margin-left: 10px; width: 52%;" %>
				</div>
				<div class="col-sm-8">
				</div>

				<!-- <input type="hidden" id="issue_user_name" value=<%= current_user.username %>> -->
				<div class="col-sm-12" style="margin-top: 10px;">
					<div class="collapse" id="new_issue_div">
						<%#=render "create"%>	
					</div>
				</div>
			</fieldset>
			<%= render "project_list" %>
	</div>  
</fieldset>