config/routes.rb
ParseRailsBoilerplate::Application.routes.draw do
  get "log_in" => "sessions#new", as: "log_in"
  get "log_out" => "sessions#destroy", as: "log_out"
  get "sign_up" => "users#new", as: "sign_up"

  resources :sessions

  resources :users do
    collection do
      get :manage
    end
  end
  
  resources :projects do
    member do
      get :archive
    end
  end

  namespace :api do
    resources :mailers do
      collection do
        post :send_mail
      end
    end
  end
  
  resources :issues do
  	collection do
  		get :fetch_issue, :pdf_report, :report, :fetch_issue_report, :sample_issues_csv
      post :upload_issues
  	end
  end

  root to: "issues#index"
end

app/models/project.rb
class Project < ParseResource::Base
	
  fields :ProjectName, :Archived
  validates :ProjectName, presence: true

  def self.archived
    where(Archived: true).collect { |p| p.ProjectName }
  end

  def self.active
    where(Archived: false).sort_by{|p| p.ProjectName}.collect { |p| p.ProjectName }
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

	before_filter :authenticate_user!

	def index
		@project = Project.new
		@projects = Project.all.sort_by(&:ProjectName)
	end	

	def create
		@error = nil
		@project = Project.new(params[:project])
		params[:project][:ProjectName] = params[:project][:ProjectName].strip.upcase
		params[:project][:Archived] = false
		@error = "Project should be unique, please reload page to get new projects if project is not in list" if Project.find_by_ProjectName(params[:project][:ProjectName])
		if @error.nil?
			if @project.save
				@success = "Project #{params[:project][:ProjectName]} created successfully"
			else
				@error = @project.errors
			end	
		end	
	end

	def destroy
		project = Project.find_by_objectId(params[:id])
		respond_to do |format|
			if project
				if project.destroy
					format.html { render text: "Project deleted successfully", layout: false, valid: true }
				else
					format.html { render text: "Something went wrong", layout: false, valid: false }
				end
			else
				format.html { render text: "Project deleted successfully", layout: false, valid: true }
			end
		end
	end

	def archive
		@project = Project.find_by_objectId(params[:id])
		
		respond_to do |format|
			if @project
				@project.Archived = !@project.Archived
				@project.save
				flash.now[:notice] = 'Project archived successfully!'
				format.js {render :archive}
			else
				flash.now[:error] = 'No project exist of this kind!'
				format.js {render '/shared/ajax_error'}
			end
    end

	end

end

app/views/projects/archive.js.erb
<% if @project %>
  var targetElement = "#project_<%= @project.objectId.downcase %>";
  $(targetElement).text("<%= @project.Archived ? 'Restore' : 'Archive' %>");
  $(targetElement).removeClass('hidden');
  $(targetElement).fadeOut();
  $(targetElement).fadeIn(1000);
  $(targetElement).next().addClass('hidden');
<% else %>
  console.error('Oops happened with: ', @project.objectId.downcase);
<% end %>

app/views/projects/create.js.erb
<% if @success %>
	$("#flash_create_message").empty();
  $("#flash_create_message").html("<%= escape_javascript @success%>");
  $("#flash_error_message").hide();
  $("#flash_create_message").show();
  
  $('#project_list_create_form').prepend("<li class='list-group-item list-group-item-info'><%=@project.ProjectName%><a href='javascript:;' class='p-action delete_project' data_id=<%=@project.objectId%>> <span class='badge'>delete</span></a></li>");

  $('<option>').val("<%=@project.ProjectName%>").text("<%=@project.ProjectName%>").appendTo($('#new_issue_create_form #project'));
<% end %>
<% if @error %>
  $("#flash_error_message").empty();
  $("#flash_error_message").html("<%= escape_javascript @error%>");
  $("#flash_create_message").hide();
  $("#flash_error_message").show();
<% end %>
$('#create_project_button').prop('disabled', false).html("Create Project");
$('#project_ProjectName').val('');

app/views/projects/index.html.erb
<div class="alert alert-success" id ="flash_create_message"></div>
<div class="alert alert-danger" id ="flash_error_message"></div>
<fieldset class="fieldset">
	<div class="row">
		<div class="col-md-4 col-md-offset-3">
			<%= form_for @project, class: "form-inline", remote: true do |f| %>
				<div class="form-group">
					<label class="" for="input01">Project<span class="required">*</span></label>  
					<div class="s">  
						<%= f.text_field :ProjectName, required: 'required' %>
					</div> 
				</div>
				<br />
				<button type="submit" class="btn btn-primary" id="create_project_button">
					Create Project
				</button>
			<% end %>
		</div>
		<div class="col-md-4" style="overflow: auto; height: 500px; ">
			<label for="input01">Project List</label>
			<ul class="list-group" id="project_list_create_form">
				<% @projects.each do |project|%>
					<li class="list-group-item list-group-item-info">
						<%= project.ProjectName %>
						<%= link_to "javascript:;", class: "p-action delete_project", data_id: project.objectId do %>
							<span class="badge">Delete</span>
						<% end %>
						&nbsp;&nbsp;&nbsp;
						<% paction = project.Archived ? 'Restore' : 'Archive' %>
						<%= link_to paction, archive_project_path(project.objectId), remote: true, id: "project_#{project.objectId.downcase}", class: 'p-action badge ajax_request', style: 'margin-top: 2px' %>
						<%= image_tag 'ajax-loader.gif', class: 'hidden' %>
					</li>
				<% end %>
			</ul>
		</div>
	</div>
</fieldset>