config/routes.rb
ParseRailsBoilerplate::Application.routes.draw do
  get "log_in" => "sessions#new", as: "log_in"
  get "log_out" => "sessions#destroy", as: "log_out"
  get "sign_up" => "users#new", as: "sign_up"

  resources :sessions

  resources :users do
    collection do
      get :manage
    end
  end
  
  resources :projects do
    member do
      get :archive
    end
  end

  namespace :api do
    resources :mailers do
      collection do
        post :send_mail
      end
    end
  end
  
  resources :issues do
  	collection do
  		get :fetch_issue, :pdf_report, :report, :fetch_issue_report, :sample_issues_csv
      post :upload_issues
  	end
  end

  root to: "issues#index"
end

app/views/layouts/_flash_messages.html.erb
<div id='flash-notifications' class="container-root">
  <% flash.each do |key, value| %>
    <div class="<%= flash_class(key) %> fade in">
      <a href="#" data-dismiss="alert" class="close">×</a>
      <%= value %>
    </div>
  <% end %>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to image_tag('logo_small.png', width: '67'), root_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Dashboard', root_path %></li>
        <% if current_user.isAdmin %>
          <li><%= link_to 'Manage Projects', projects_path %></li>
        <% end %>
        <li><a href="#create_new_issue" data-toggle = "modal" >Create New Cut</a></li>
        <li><a href="#import_new_issue" data-toggle = "modal" >Import Cuts</a></li>
        <li><%= link_to 'Reset Password', edit_user_path(current_user.objectId) %></li>
        <% if can? :new, User %>
          <li><%= link_to 'Create User', sign_up_path %></li>
          <li><%= link_to 'Report', report_issues_path %></li>
        <% end %>
        <li><%= link_to 'Logout', log_out_path %></li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>  
<html>  
  <head>  
    <title>Death By Thousand Cuts</title>
    <%= stylesheet_link_tag "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tag %>
  </head>  
  <body> 

    <% if current_user %>
      <%= render "layouts/navbar" %>
    <% end %>

    <%= render 'layouts/flash_messages' %>

    <div class="container-fluid container-root">
      <% if current_user %>
        <span id="welcome">Hi, <%= current_user.Name %></span>
      <% end -%>
    	<%= yield %>
      <% if current_user %>
        <input type="hidden" id="issue_user_name" value=<%= current_user.username %>>
        <div class="modal fade" id="create_new_issue" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
          <div class="modal-dialog" style="width: 65%;">
            <div class="modal-content" >
              <div class="modal-header" style="background-color: #428BCA;height: 47px;">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                Create New Cut  
              </div>
              <div class="modal-body" style="height: 350px;">
                <%= render "/issues/create" %>
              </div>
              <div class="modal-footer" style="background-color: whiteSmoke;">
                <button type="button" data-dismiss="modal" class="btn">Close</button>
                <button type="button" class="btn btn-primary"  id ="create_issue">Create</button>
              </div>
            </div><!-- /.modal-content -->
          </div><!-- /.modal-dialog -->  
        </div>

        <div class="modal fade" id="import_new_issue" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
          <div class="modal-dialog" style="width: 65%;">
            <div class="modal-content" >
              <div class="modal-header" style="background-color: #428BCA;height: 47px;">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                Import New Cuts  
              </div>
              <div class="modal-body" style="height: 60px;">
                <%= form_tag upload_issues_issues_path, id: "upload_cuts_file_form", multipart: true do %>
                  <span class="wrap1">
                    <%= file_field_tag :file, accept: 'text/csv', class: "btn"%>
                  </span>
                <% end %>
                <div class="control-group">
                  <div class="col-sm-12">
                  <b class='downloadCompanySample'><a class='downloadCompanySample' href="/issues/sample_issues_csv">Click here</a></b> to download sample format of CSV file.
                  </div>  
                </div>
              </div>
              <div class="modal-footer" style="background-color: whiteSmoke;">
                <button type="button" data-dismiss="modal" class="btn">Close</button>
                <button type="button" class="btn btn-primary"  id ="upload_issue" 
                 onclick="javascript: $('#upload_cuts_file_form').submit();">Upload</button>
              </div>
            </div><!-- /.modal-content -->
          </div><!-- /.modal-dialog -->  
        </div>
      <%end%> 

    </div>
    
  </body>  
</html>  